<?php

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../libs/autoload.php';


$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
#$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(__DIR__ . '/../log');

// Specify folder for cache
$configurator->setTempDirectory(__DIR__ . '/../temp');

// Enable RobotLoader - this will load all classes automatically
$loader = $configurator->createRobotLoader()
	->addDirectory(__DIR__);

$loader->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');

$localConfigurationFile = __DIR__ . '/config/config.local.neon';

// Check if local configuration is set
if (!file_exists($localConfigurationFile) || !is_readable($localConfigurationFile)) {
    if (php_sapi_name() == "cli") {
        echo "Configuration file [" . $localConfigurationFile . "] does not exist or isn't readable!\n";
        exit(1);
    } else {
        trigger_error(
            "Configuration file [" . $localConfigurationFile . "] does not exist or isn't readable!",
            E_ERROR
        );
    }
}

$configurator->addConfig(__DIR__ . '/config/config.local.neon', $configurator::NONE); // none section
$container = $configurator->createContainer();

$container->application->catchExceptions = !$configurator->isDebugMode();

return $container;
